#!/bin/bash
# description: Glassfish Start Stop Restart
# processname: glassfish
# chkconfig: 234 20 80
JAVA_HOME=[java_home]
export JAVA_HOME
PATH=$JAVA_HOME/bin:$PATH
export PATH
GLASSFISH_HOME=[glassfish_home]

case $1 in
start)
sh $GLASSFISH_HOME/bin/asadmin start-domain [domain_name]
;;
stop)
sh $GLASSFISH_HOME/bin/asadmin stop-domain [domain_name] 
;;
restart)
sh $GLASSFISH_HOME/bin/asadmin stop-domain [domain_name] 
sh $GLASSFISH_HOME/bin/asadmin start-domain [domain_name]
;;
esac
exit 0
